<?php

namespace AppBundle\Repository;

/**
 * TomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TomRepository extends \Doctrine\ORM\EntityRepository
{
}
