<?php

namespace AppBundle\Repository;

/**
 * TomsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TomsRepository extends \Doctrine\ORM\EntityRepository
{
}
