<?php

namespace AppBundle\Repository;

/**
 * UerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UerRepository extends \Doctrine\ORM\EntityRepository
{
}
